### ISSUE TITLE
Blender hangs after clicking the Bake Button

### ISSUE THREAD

**Issue by TehraniX** [batFINGER/batFINGER-blender-addons#5]
I have the following problem:

1. I add the addon
2. I add a speaker to the scene
3. I attach a sound file to the speaker

Now if I press the Bake Button in the properties menu, Blender hangs.

I am using Blender on my Macbook Pro (Mid 2014).

I have even started Blender via the Terminal to see if there is any kind of informative output, but there is nothing of interest regarding this issue. The last line is about me saving the user preferences and that's it.

I am using Blender 2.79.

Any idea why that is happening?

I have attached a screenshot:

<img width="1440" alt="bildschirmfoto 2018-10-16 um 11 53 04" src="https://user-images.githubusercontent.com/9861790/47008227-35757a80-d13a-11e8-99f6-57fa3195b5ad.png">

**Comment by TehraniX** [comment]
I justed tried to stop Blender in the Terminal and I got the following output. Maybe that is helpful. There seems to be some issues with the GUI.

```console
  File "/Applications/Blender_old/blender.app/Contents/Resources/2.79/scripts/addons/sound_drivers/sound_bake.py", line 210, in draw
    self.draw_area_buttons(context)
  File "/Applications/Blender_old/blender.app/Contents/Resources/2.79/scripts/addons/sound_drivers/screen_panels.py", line 114, in draw_area_buttons
    root = self.build_tree(context)
  File "/Applications/Blender_old/blender.app/Contents/Resources/2.79/scripts/addons/sound_drivers/screen_panels.py", line 56, in build_tree
    areas = sorted(areas, key = lambda k:(k.x , k.y))
KeyboardInterrupt

location: <unknown location>:-1




  File "/Applications/Blender_old/blender.app/Contents/Resources/2.79/scripts/addons/sound_drivers/sound_bake.py", line 210, in draw
    self.draw_area_buttons(context)
  File "/Applications/Blender_old/blender.app/Contents/Resources/2.79/scripts/addons/sound_drivers/screen_panels.py", line 114, in draw_area_buttons
    root = self.build_tree(context)
  File "/Applications/Blender_old/blender.app/Contents/Resources/2.79/scripts/addons/sound_drivers/screen_panels.py", line 59, in build_tree
    sh = [a for a in areas if a != area and a.x == area.x and a.w == area.w]
KeyboardInterrupt

location: <unknown location>:-1




^CTraceback (most recent call last):
  File "/Applications/Blender_old/blender.app/Contents/Resources/2.79/scripts/addons/sound_drivers/sound_bake.py", line 210, in draw
    self.draw_area_buttons(context)
  File "/Applications/Blender_old/blender.app/Contents/Resources/2.79/scripts/addons/sound_drivers/screen_panels.py", line 114, in draw_area_buttons
    root = self.build_tree(context)
  File "/Applications/Blender_old/blender.app/Contents/Resources/2.79/scripts/addons/sound_drivers/screen_panels.py", line 45, in build_tree
    se = [a for a in areas if a != area and a.y == area.y and a.h == area.h]
  File "/Applications/Blender_old/blender.app/Contents/Resources/2.79/scripts/addons/sound_drivers/screen_panels.py", line 45, in <listcomp>
    se = [a for a in areas if a != area and a.y == area.y and a.h == area.h]
KeyboardInterrupt

location: <unknown location>:-1
```

**Comment by TehraniX** [comment]
I would like to mention, that I tried the addon in Blender 2.79, 2.78c, 2.78, 2.76b. It did not work for any of those versions.

**Comment by TehraniX** [comment]
Ok, I have found the issue, I have to download the official 1.1 release of the sound driver from Github, instead of download the master branch.
